<html>
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<link href="css/reset.css" rel="stylesheet">
	<link href="css/video-js-5.7.1.css" rel="stylesheet">
	<link href="http://videojs.github.io/font/css/videojs-icons.css" rel="stylesheet">
	<link href="css/jquery.jscrollpane.css" rel="stylesheet" media="all" />
	<link href="css/videojs-resolution-switcher.css" rel="stylesheet">
	<link href="css/videojs-audiotrack-switcher.css" rel="stylesheet">
	<link href="css/videojs.ads.css" rel="stylesheet" type="text/css">
	<link href="css/videojs.vast.css" rel="stylesheet" type="text/css">
	<link href='css/videojs.errors.css' rel='stylesheet'>
	<link href='css/video-js-resolutions.css' rel='stylesheet'>
	<link href='css/videojs.progressTips.css' rel='stylesheet'>
	<script type="text/javascript" src="http://bt.3tv.im/dash/js/swfobject.js"></script>
	<script type="text/javascript" src="http://bt.3tv.im/dash/js/ParsedQueryString.js"></script>
	<script src="http://bt.3tv.im/dash/js/jquery_1.8.3.js"></script>
	<script src="http://bt.3tv.im/dash/js/jquery.contextmenu.js"></script>
	<script src="http://bt.3tv.im/dash/js/jquery.jscrollpane.min.js"></script>
	<script src="http://bt.3tv.im/dash/js/jquery.mousewheel.js"></script>
    
</head>
<body>
<?php echo $this->layout()->content ?>

    <script>
        var FileListId = '<?php echo $this->layout()->fileId; ?>';
    </script>
<script src="http://bt.3tv.im/dash/js/js/video.js"></script>
  <script src="http://bt.3tv.im/dash/js/js/hls.js"></script> 
  <script src="http://bt.3tv.im/dash/js/js/videojs-hlsjs.js"></script>
  <script src="http://bt.3tv.im/dash/js/js/videojs-resolution-switcher.js"></script>
  <script src="http://bt.3tv.im/dash/js/js/videojs-audio-switcher.js"></script>
  <script src="http://bt.3tv.im/dash/js/js/vast-client.js"></script>
  <script src="http://bt.3tv.im/dash/js/js/vast/video.ads.js"></script>
  <script src="http://bt.3tv.im/dash/js/js/vast/videojs.vast.js"></script>
  <script src="http://bt.3tv.im/dash/js/js/videojs-playlists-old.js"></script>
  <script src="http://bt.3tv.im/dash/js/js/videojs.hotkeys.js"></script>
  <script src="http://bt.3tv.im/dash/js/js/canvas.js"></script>
  <script src="http://bt.3tv.im/dash/js/js/metrics.js"></script>
  <script src="http://bt.3tv.im/dash/js/js/jsonpack.js"></script>
  <script src="http://bt.3tv.im/dash/js/js/js.cookie.js"></script>
  <script src="http://bt.3tv.im/dash/js/js/app_old.js"></script>
  <script src="http://bt.3tv.im/dash/js/js/app-plugins.js"></script>
  <script src="http://bt.3tv.im/dash/js/js/app.js"></script>

</body>
</html>